# Generated by Django 4.2.19 on 2025-04-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('form_class', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=1)),
                ('subject', models.CharField(choices=[('ENG', 'English'), ('MATH', 'Mathematics'), ('SCI', 'Science'), ('CHI', 'Chinese'), ('PE', 'Physical Education'), ('MUS', 'Music'), ('ART', 'Art')], max_length=4)),
                ('mark', models.PositiveSmallIntegerField()),
                ('conduct', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Satisfactory'), ('D', 'Needs Improvement')], max_length=1)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='records.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester', 'subject', 'academic_year')},
            },
        ),
    ]
