# Generated by Django 4.2.19 on 2025-04-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_studentprofile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicrecord',
            options={'ordering': ['student', 'academic_year', 'semester'], 'verbose_name': 'Academic Record', 'verbose_name_plural': 'Academic Records'},
        ),
        migrations.AlterUniqueTogether(
            name='academicrecord',
            unique_together={('student', 'semester', 'academic_year')},
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='Chinese',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='English',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='Mathematics',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='Science',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='academicrecord',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='academicrecord',
            name='subject',
        ),
    ]
