# Generated by Django 4.2.19 on 2025-04-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_academicrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='records.studentprofile'),
        ),
    ]
