# Generated by Django 4.2.19 on 2025-04-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_academicrecord_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('form_class', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='records.studentprofile')),
            ],
            options={
                'ordering': ['academic_year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
