# Generated by Django 4.2.19 on 2025-04-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_migrate_class_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclasshistory',
            options={'get_latest_by': 'academic_year', 'ordering': ['student', '-academic_year']},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='form_class',
        ),
        migrations.AddField(
            model_name='studentclasshistory',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
