# Generated by Django 4.2.19 on 2025-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_studentclasshistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasshistory',
            name='academic_year',
            field=models.PositiveSmallIntegerField(help_text='The starting year of the academic year (e.g. 2022 for 2022-2023)'),
        ),
    ]
