# Generated by Django 4.2.19 on 2025-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_studentclasshistory_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasshistory',
            name='student_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
