# Generated by Django 4.2.19 on 2025-04-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_studentclasshistory_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasshistory',
            name='student',
            field=models.ForeignKey(help_text='Reference by student ID (e.g. S0001)', on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='records.studentprofile'),
        ),
    ]
