# Generated by Django 4.2.19 on 2025-04-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_studentclasshistory_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclasshistory',
            name='student_name',
        ),
        migrations.AlterField(
            model_name='studentclasshistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='records.studentprofile'),
        ),
    ]
