# Generated by Django 4.2.19 on 2025-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_studentclasshistory_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasshistory',
            name='student_id_cache',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
    ]
