# Generated by Django 4.2.19 on 2025-04-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_populate_student_id_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclasshistory',
            name='student_id_cache',
        ),
    ]
