# Generated by Django 4.2.19 on 2025-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_studentclasshistory_student_id_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasshistory',
            name='student_name',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
