# Generated by Django 4.2.19 on 2025-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_remove_studentclasshistory_student_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='academic_year',
            field=models.PositiveSmallIntegerField(choices=[(2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025')]),
        ),
        migrations.AlterField(
            model_name='studentclasshistory',
            name='academic_year',
            field=models.PositiveSmallIntegerField(choices=[(2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025')], help_text='The starting year of the academic year (e.g. 2022 for 2022-2023)'),
        ),
    ]
